### ISSUE TITLE
Would be better if there was an ALIAS library in cmakelists

### ISSUE THREAD

**Issue by xhuw** [xmos/lib_qspi_fast_read#17]
Currently if you add fwk_rtos to your project and forget to add lib_qspi_fast_read then you get a confusing compile time error. This is because cmake does not know whether the library that is being linked should have been declared by cmake or if it already exists on the system.

If you use an alias library with the `::` in it, then cmake will instead give you this helpful error:

```cmake
CMake Error at CMakeLists.txt:6 (target_link_libraries):
  Cannot specify link libraries for target "foo::foo" which is not built by
  this project.
```

So my request is that this library includes a cmake alias that is used everywhere else. Thanks :)

**Comment by xmos-jmccarthy** [comment]
Closing as this issue is tied with the pending build system changes from Ross and Daniel.  This is a known issue that the new setup is supposed to resolve.

The business intended use case for fwk_rtos is not standalone and only as a subset of sln_voice or xcore_iot.  Since we cannot have fwk_rtos be a mono repo that submodules all of it's dependencies it is up to the application above to ensure that it has the appropriate libraries.
